### ISSUE TITLE
既然开源为什么不开的彻底一些！

### ISSUE THREAD

**Issue by wayne798** [pili-engineering/PLStreamingKit#4]
现在百度有百度云的推流sdk，网易有网易云的sdk，这些不要脸的大公司把这些东西弄出来卖钱。为啥不能像bilibili开源的ijkplayer一样，让小公司有更多的选择！所以，既然开了为啥不把代码都开源出来啊？！

**Comment by peiweichen** [comment]
百度云的推流sdk
@wayne798  是免费的 亲

**Comment by Phunk87** [comment]
@wayne798 当前的方式对推流到七牛云直播服务产生什么不可解决的问题了吗？如果是请附带对应问题。另外 PLStreamingKit 以 Apache v2 作为许可协议提供，不排除商业授权提供源码的方式，谢谢。
