### ISSUE TITLE
fail to start streaming.

### ISSUE THREAD

**Issue by loretoparisi** [pili-engineering/PLStreamingKit#6]
I get an error when running both the audio & video examples:

`2016-03-04 18:45:29.502 PLStreamingKit_Example[351:89896] fail to start streaming`

**Comment by Phunk87** [comment]
PLStreamingKit is bind to Qiniu Live Streaming Service. Currently, you can not push to other server yet.

**Comment by loretoparisi** [comment]
@0dayZh ok thank you.
