### ISSUE TITLE
1.1.5版本如何设置流地址？

### ISSUE THREAD

**Issue by youyisx** [pili-engineering/PLStreamingKit#9]
您好！之前一直用的1.0的版本，可以直接在start函数中 传入pushUrl做为推流的地址。现在1.1.5版本，没有看见在何处可以设置这个地址呢，
PLStream 这个对象里有属性 都必须设置的么？如果没有怎么办，我现在就只有推流的地址，其它参数没有呢

**Comment by Phunk87** [comment]
请参看 wiki：https://github.com/pili-engineering/PLStreamingKit/wiki#5-前置条件
